version: '3.10'

services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #     - "443:443"
  #   volumes:
  #     - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /etc/ssl/merged_certificate.crt:/etc/ssl/merged_certificate.crt:ro
  #     - /etc/ssl/private/private.key:/etc/ssl/private/private.key:ro
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network

  app:
    image: kooqooo/hello-jobits:latest
    ports:
      - "8501:8501"
      - "8001:8001"
    volumes:
      - ~/data:/app/data
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
